version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: "15.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: sudo gem install cocoapods
      - run:
          name: Install Pods
          command: pod install
      - run:
          name: Build and Test
          command: |
            set -o pipefail
            xcodebuild -workspace DigioStore.xcworkspace -scheme DigioStore -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max,OS=17.0' build test | xcpretty
      - store_artifacts:
          path: output

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
